syntax = "proto3";

package kyc;

enum DocumentType {
  UNKNOWN = 0;
  NIC = 1;
  PASSPORT = 2;
}

message ProcessDocumentRequest {
    bytes file = 1;
    string file_name = 2;
    DocumentType document_type = 3;
}

message KycResponse {
    string raw_text = 1;

    DocumentType document_type = 2;

    repeated KycField fields = 3;
    float overall_confidence = 4;

    bool is_valid = 5;
    string error = 6;
}

message KycField {
  string key = 1;
  string value = 2;
  float confidence = 3;
}

service KycService {
    rpc ProcessDocument(ProcessDocumentRequest) returns (KycResponse);
}